apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx
  labels:
    app.kubernetes.io/name: myapp-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp-nginx
    spec:
      containers:
      - name: myapp-nginx
        image: artemsalnikov/myapp-nginx:latest
        ports:
        - containerPort: 80
